### ISSUE TITLE
Wrong directories mapping when using Composer

### ISSUE THREAD

**Issue by winkelsdorf** [fballiano/magento-autodelete-product-images#1]
When I install this Extension using Composer, the files are mapped to wrong directories:

/app/code/code/code/community/Fballiano/AutodeleteProductImages/*
/app/code/code/community/Fballiano/AutodeleteProductImages/*
and
/app/etc/etc/modules/Fballiano_AutodeleteProductImages.xml

Instead of
/app/code/community/Fballiano/AutodeleteProductImages/*
and
/app/etc/modules/Fballiano_AutodeleteProductImages.xml

Maybe there's something wrong with your composer.json or modman file? 

Tried under fresh 1.9.0.1.

**Comment by winkelsdorf** [comment]
It's in the modman file, remove

``` code
app/*       app
```

and add the following:

``` code
app/code/community/Fballiano/AutodeleteProductImages  app/code/community/Fballiano/AutodeleteProductImages
app/etc/modules/Fballiano_AutodeleteProductImages.xml app/etc/modules/Fballiano_AutodeleteProductImages.xml
```

**Comment by fballiano** [comment]
Hi,
sorry for the problem and thank you very much for the fix!

**Comment by winkelsdorf** [comment]
You're welcome. Thank you for this great extension!
